services:
  db:
    restart: always
    image: mongo:latest
    ports:
      - '27026:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - "/home/hust/bkfintech/db:/data/db"
    logging:
      driver: none
