services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "/home/hust/bkfintech/media:/app/media"
    ports:
      - "3003:3000"
  db:
    restart: always
    image: mongo:latest
    ports:
      - '27026:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - "/home/hust/bkfintech/db:/data/db"
    logging:
      driver: none
