/**
 * BỘ MẪU KIỂM THỬ HỢP NHẤT — 616 câu.
 *
 * Gộp từ hai bộ trước (400 câu phủ rộng + 200 câu đào sâu vào các nhóm đã đo
 * được là yếu). Hai file nguồn đã bị xoá sau khi hợp nhất; đây là nguồn duy
 * nhất từ nay.
 *
 * CẤU TRÚC
 * --------
 *   q         câu hỏi được chấm
 *   history   các lượt hỏi TRƯỚC đó (chỉ phần người dùng). Thiếu = lượt đầu.
 *   group     nhóm, dùng để đọc báo cáo theo từng kiểu câu hỏi
 *   expect    hành vi đúng ở mức ĐẦU-CUỐI: trả lời / từ chối vì thiếu dữ liệu /
 *             hỏi lại vì mơ hồ / không tìm thấy gì
 *   gold      chỉ có ở câu `expect: "answer"`. Điều kiện để một chunk được
 *             tính là CHỨA ĐÁP ÁN — dùng cho các chỉ số truy hồi (Hit@k, MRR,
 *             P@7). Khớp `url` HOẶC `text` là đủ.
 *
 * VÌ SAO `gold` CHẤM THEO NỘI DUNG, KHÔNG THEO MỘT URL DUY NHẤT
 * -------------------------------------------------------------
 * Tra corpus cho thấy đáp án nằm rải nhiều trang: "Đỗ Bá Lâm" có trong 19
 * chunk, "Hackday" trong 40, phần lớn là tin tức chứ không phải trang hồ sơ.
 * Chấm theo một URL sẽ đánh trượt những lượt truy hồi thực ra hoàn toàn đúng.
 * Định nghĩa dùng ở đây là chuẩn của open-domain QA: một chunk tính là ĐÚNG
 * nếu nó thật sự chứa đáp án.
 *
 * So khớp trên `raw`, KHÔNG trên `content`: `content` mang thêm phần header
 * do build-index tự sinh, nên chấm trên đó khiến mọi chunk của một báo cáo đều
 * "chứa" tên báo cáo đó.
 *
 * 207/600 câu có nhãn vàng; các chỉ số truy hồi chỉ tính trên
 * phần này. Câu `not_updated`/`no_answer`/`nothing_found` cố ý KHÔNG có nhãn —
 * với chúng, hành vi đúng là từ chối, và điều đó được đo bằng chỉ số riêng.
 */

export type Expect = "answer" | "not_updated" | "no_answer" | "nothing_found";

export interface Gold {
  /** Nguồn regex, so với `raw` của chunk, không phân biệt hoa thường. */
  text?: string[];
  /** Chuỗi con của URL. */
  url?: string[];
}

export interface Case {
  id: number;
  q: string;
  history?: string[];
  group: string;
  expect: Expect;
  gold?: Gold;
}

export const SAMPLES: Case[] = [
  { id:1, q:"BK Fintech là gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:2, q:"Viện Công nghệ và Kinh tế số là gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:3, q:"Đây là trang của ai vậy?", group:"01. Người mới vào trang", expect:"answer" },
  { id:4, q:"Viện này làm gì?", group:"01. Người mới vào trang", expect:"answer" },
  { id:5, q:"Giới thiệu về Viện", group:"01. Người mới vào trang", expect:"answer" },
  { id:6, q:"Viện thuộc trường nào?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["Bách khoa|Hanoi University of Science"]} },
  { id:7, q:"BK Fintech trực thuộc đâu?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["Bách khoa|Hanoi University of Science"]} },
  { id:8, q:"Viện có những hoạt động gì?", group:"01. Người mới vào trang", expect:"answer" },
  { id:9, q:"Tôi có thể tìm hiểu gì ở đây?", group:"01. Người mới vào trang", expect:"answer" },
  { id:10, q:"Trang này có thông tin gì?", group:"01. Người mới vào trang", expect:"answer" },
  { id:11, q:"Viện đào tạo về lĩnh vực nào?", group:"01. Người mới vào trang", expect:"answer" },
  { id:12, q:"BK Fintech chuyên về cái gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:13, q:"Fintech là gì?", group:"01. Người mới vào trang", expect:"answer" },
  { id:14, q:"Kinh tế số là gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:15, q:"Viện có dạy học không?", group:"01. Người mới vào trang", expect:"answer" },
  { id:16, q:"Ở đây có khóa học nào không?", group:"01. Người mới vào trang", expect:"answer", gold:{"url":["/courses/"]} },
  { id:17, q:"Muốn học ở đây thì làm sao?", group:"01. Người mới vào trang", expect:"answer" },
  { id:18, q:"Viện có nghiên cứu gì không?", group:"01. Người mới vào trang", expect:"answer" },
  { id:19, q:"Tầm nhìn của Viện là gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"url":["about/vision-and-operating-philosophy","about/welcome-message"]} },
  { id:20, q:"Sứ mệnh của Viện là gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"url":["about/vision-and-operating-philosophy","about/welcome-message"]} },
  { id:21, q:"Viện nằm ở đâu?", group:"01. Người mới vào trang", expect:"answer" },
  { id:22, q:"Địa chỉ của Viện?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:23, q:"Liên hệ với Viện bằng cách nào?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:24, q:"Email của Viện là gì?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:25, q:"Viện có website riêng không?", group:"01. Người mới vào trang", expect:"answer" },
  { id:26, q:"Ai lãnh đạo Viện?", group:"01. Người mới vào trang", expect:"answer" },
  { id:27, q:"Viện có bao nhiêu người?", group:"01. Người mới vào trang", expect:"not_updated" } /* corpus không nêu tổng nhân sự — đã soát chunks_all.jsonl 2026-08-21 */,
  { id:28, q:"Viện có gì nổi bật?", group:"01. Người mới vào trang", expect:"answer" },
  { id:29, q:"Tại sao nên chọn BK Fintech?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:30, q:"Viện có hợp tác quốc tế không?", group:"01. Người mới vào trang", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:31, q:"Liệt kê tất cả các khóa học của Viện", group:"02. Liệt kê", expect:"answer", gold:{"url":["/courses/"]} },
  { id:32, q:"Viện có những khóa học ngắn hạn nào?", group:"02. Liệt kê", expect:"answer", gold:{"url":["/courses/"]} },
  { id:33, q:"Kể tên các phòng lab của Viện", group:"02. Liệt kê", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:34, q:"Viện có mấy phòng lab, tên là gì?", group:"02. Liệt kê", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:35, q:"Các giải pháp công nghệ của Viện gồm những gì?", group:"02. Liệt kê", expect:"answer" },
  { id:36, q:"Liệt kê các sản phẩm phần mềm của Viện", group:"02. Liệt kê", expect:"answer" },
  { id:37, q:"Viện có những dự án nghiên cứu nào?", group:"02. Liệt kê", expect:"answer" },
  { id:38, q:"Các sự kiện thường niên của Viện là gì?", group:"02. Liệt kê", expect:"answer" },
  { id:39, q:"Viện tổ chức những cuộc thi nào?", group:"02. Liệt kê", expect:"answer" },
  { id:40, q:"Kể tên các thành viên Ban Giám đốc", group:"02. Liệt kê", expect:"answer" },
  { id:41, q:"Danh sách Hội đồng cố vấn gồm những ai?", group:"02. Liệt kê", expect:"answer", gold:{"text":["David Tran"]} },
  { id:42, q:"Hội đồng Viện có những thành viên nào?", group:"02. Liệt kê", expect:"answer", gold:{"url":["about/institute-council"]} },
  { id:43, q:"Các nhà nghiên cứu của Viện gồm những ai?", group:"02. Liệt kê", expect:"answer", gold:{"url":["about/researchers-and-assistants"]} },
  { id:44, q:"Bộ phận hành chính có những ai?", group:"02. Liệt kê", expect:"answer" },
  { id:45, q:"Viện có những ấn phẩm nào?", group:"02. Liệt kê", expect:"answer" },
  { id:46, q:"Liệt kê các số báo cáo Vietnam Digital Economy Review", group:"02. Liệt kê", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:47, q:"Các hoạt động học thuật của Viện gồm những gì?", group:"02. Liệt kê", expect:"answer", gold:{"url":["/academic"]} },
  { id:48, q:"Viện có những câu lạc bộ nào?", group:"02. Liệt kê", expect:"answer", gold:{"url":["get-involved/club"]} },
  { id:49, q:"Các workshop của Viện gồm những chủ đề gì?", group:"02. Liệt kê", expect:"answer", gold:{"url":["get-involved/workshop-series"]} },
  { id:50, q:"Liệt kê các mùa của BK Fintech Hackday", group:"02. Liệt kê", expect:"answer", gold:{"text":["Hackday"]} },
  { id:51, q:"Viện có những đối tác nào?", group:"02. Liệt kê", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:52, q:"Các doanh nghiệp đã hợp tác với Viện là ai?", group:"02. Liệt kê", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:53, q:"Kể tên các trường đại học hợp tác với Viện", group:"02. Liệt kê", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:54, q:"Các module của khóa Business Intelligence là gì?", group:"02. Liệt kê", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:55, q:"Khóa Fintech gồm những nội dung nào?", group:"02. Liệt kê", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:56, q:"Liệt kê các chủ đề của hội thảo ECOTECH", group:"02. Liệt kê", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:57, q:"Các diễn giả của ECOTECH 2025 gồm những ai?", group:"02. Liệt kê", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:58, q:"Viện có những cơ sở vật chất gì?", group:"02. Liệt kê", expect:"answer", gold:{"url":["academic/facility"]} },
  { id:59, q:"Các hình thức học của Viện gồm những gì?", group:"02. Liệt kê", expect:"answer" },
  { id:60, q:"Liệt kê các lĩnh vực nghiên cứu của Viện", group:"02. Liệt kê", expect:"answer" },
  { id:61, q:"Khóa Business Intelligence kéo dài bao nhiêu giờ?", group:"03. Chi tiết", expect:"answer", gold:{"text":["30 hours","30 giờ"]} },
  { id:62, q:"Khóa Business Intelligence học những gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:63, q:"Khóa Business Intelligence học online hay offline?", group:"03. Chi tiết", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:64, q:"Khóa Business Intelligence học ở đâu?", group:"03. Chi tiết", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:65, q:"Khóa Fintech kéo dài bao lâu?", group:"03. Chi tiết", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:66, q:"Khóa Fintech dành cho đối tượng nào?", group:"03. Chi tiết", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:67, q:"Khóa Data Analysis dạy những công cụ gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["courses/data-analysis"]} },
  { id:68, q:"Khóa AI for Everyone dành cho ai?", group:"03. Chi tiết", expect:"not_updated" } /* không có trang courses/ai-for-everyone; /academic chỉ có một dòng mô tả, không nêu đối tượng */,
  { id:69, q:"Khóa AI, Blockchain & Fintech for Beginners học gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["ai-blockchain-fintech-for-beginners"]} },
  { id:70, q:"Chương trình Trải nghiệm ngành IT dành cho ai?", group:"03. Chi tiết", expect:"answer", gold:{"url":["level-up-it"]} },
  { id:71, q:"Chương trình Trải nghiệm ngành IT có mục tiêu gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["level-up-it"]} },
  { id:72, q:"V-Chain là gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:73, q:"V-Chain giải quyết vấn đề gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:74, q:"V-Chain hỗ trợ những mạng blockchain nào?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:75, q:"Các dịch vụ lõi của V-Chain là gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:76, q:"eDiploma dùng để làm gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:77, q:"eDiploma giải quyết vấn đề gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:78, q:"BKSign là giải pháp gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:79, q:"BKSign dùng công nghệ gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:80, q:"BKOffice có những tính năng gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["solutions/BKOffice"],"text":["BKOffice"]} },
  { id:81, q:"Phòng lab Smart Finance nghiên cứu gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["Smart Finance and Digital Banking"]} },
  { id:82, q:"Lab Software Engineering and Decentralized Systems làm gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["Decentralized Systems"]} },
  { id:83, q:"OE-Fin Lab nghiên cứu về cái gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["Operational Efficiency in Finance"]} },
  { id:84, q:"Dự án Cyber Clinic là gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:85, q:"Dự án Cyber Clinic kéo dài bao lâu?", group:"03. Chi tiết", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:86, q:"Cyber Clinic dành cho đối tượng nào?", group:"03. Chi tiết", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:87, q:"Điều kiện tham gia Cyber Clinic là gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:88, q:"Cyber Clinic có gì cho doanh nghiệp?", group:"03. Chi tiết", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:89, q:"Cyber Clinic có gì cho giảng viên?", group:"03. Chi tiết", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:90, q:"Hội thảo ECOTECH có chủ đề gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:91, q:"BK Fintech Hackday là cuộc thi gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["Hackday"]} },
  { id:92, q:"Vietnam Digital Economy Review là ấn phẩm gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:93, q:"Báo cáo Vietnam Digital Economy Review 2025 nói về gì?", group:"03. Chi tiết", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:94, q:"Cơ sở vật chất của Viện như thế nào?", group:"03. Chi tiết", expect:"answer", gold:{"url":["academic/facility"]} },
  { id:95, q:"Viện có phòng lab đặt ở đâu?", group:"03. Chi tiết", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:96, q:"Hoạt động học thuật của Viện gồm những gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["/academic"]} },
  { id:97, q:"Câu lạc bộ của Viện hoạt động thế nào?", group:"03. Chi tiết", expect:"answer", gold:{"url":["get-involved/club"]} },
  { id:98, q:"Chuỗi workshop của Viện có nội dung gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["get-involved/workshop-series"]} },
  { id:99, q:"Tầm nhìn và triết lý hoạt động của Viện là gì?", group:"03. Chi tiết", expect:"answer", gold:{"url":["about/vision-and-operating-philosophy","about/welcome-message"]} },
  { id:100, q:"Thông điệp chào mừng của Viện nói gì?", group:"03. Chi tiết", expect:"answer" },
  { id:101, q:"Viện có bao nhiêu phòng lab?", group:"04. Thống kê", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:102, q:"Viện có bao nhiêu khóa học ngắn hạn?", group:"04. Thống kê", expect:"answer", gold:{"url":["/courses/"]} },
  { id:103, q:"Khóa Business Intelligence có mấy module?", group:"04. Thống kê", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:104, q:"Khóa Business Intelligence bao nhiêu giờ?", group:"04. Thống kê", expect:"answer", gold:{"text":["30 hours","30 giờ"]} },
  { id:105, q:"Khóa Fintech có bao nhiêu giờ học và bao nhiêu giờ workshop?", group:"04. Thống kê", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:106, q:"Dự án Cyber Clinic kéo dài bao nhiêu tháng?", group:"04. Thống kê", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:107, q:"Cyber Clinic đào tạo bao nhiêu học viên?", group:"04. Thống kê", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:108, q:"BK Fintech Hackday đã tổ chức đến mùa thứ mấy?", group:"04. Thống kê", expect:"answer", gold:{"text":["Hackday"]} },
  { id:109, q:"Tổng giải thưởng của HACK CX IN BANKING TOGETHER 2026 là bao nhiêu?", group:"04. Thống kê", expect:"answer", gold:{"text":["Hackathon|HACK <CX>"]} },
  { id:110, q:"Ban Giám đốc Viện có mấy người?", group:"04. Thống kê", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:111, q:"Hội đồng cố vấn có bao nhiêu thành viên?", group:"04. Thống kê", expect:"answer", gold:{"text":["David Tran"]} },
  { id:112, q:"Báo cáo Vietnam Digital Economy Review có mấy số?", group:"04. Thống kê", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:113, q:"Viện có bao nhiêu giải pháp công nghệ?", group:"04. Thống kê", expect:"answer" },
  { id:114, q:"Viện có bao nhiêu sinh viên đang theo học?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:115, q:"Học phí khóa Business Intelligence là bao nhiêu tiền?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:116, q:"Học phí khóa Fintech bao nhiêu?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:117, q:"Viện có bao nhiêu nhân viên toàn thời gian?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:118, q:"Ngân sách hoạt động của Viện một năm là bao nhiêu?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:119, q:"Tỷ lệ học viên có việc làm sau khóa học là bao nhiêu phần trăm?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:120, q:"Viện đã đào tạo tổng cộng bao nhiêu học viên?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:121, q:"Doanh thu của Viện năm 2025 là bao nhiêu?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:122, q:"Có bao nhiêu doanh nghiệp đã ký hợp đồng với Viện?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:123, q:"Khóa học tiếp theo khai giảng ngày nào?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:124, q:"Số lượng bài báo khoa học Viện công bố năm nay là bao nhiêu?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:125, q:"Viện xếp hạng thứ mấy trong các viện nghiên cứu Việt Nam?", group:"04. Thống kê — corpus không có", expect:"not_updated" },
  { id:126, q:"Viện trưởng của BK Fintech là ai?", group:"05. Về người", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:127, q:"Ai là Viện trưởng Viện Công nghệ và Kinh tế số?", group:"05. Về người", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:128, q:"Phó Viện trưởng của Viện gồm những ai?", group:"05. Về người", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:129, q:"Ai là Phó Viện trưởng phụ trách đào tạo?", group:"05. Về người", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:130, q:"Chủ tịch Hội đồng cố vấn của Viện là ai?", group:"05. Về người", expect:"answer", gold:{"text":["David Tran"]} },
  { id:131, q:"Ai đứng đầu Hội đồng Viện?", group:"05. Về người", expect:"answer", gold:{"url":["about/institute-council"]} },
  { id:132, q:"Thầy Đỗ Bá Lâm giữ chức vụ gì?", group:"05. Về người", expect:"answer", gold:{"text":["Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:133, q:"Cô Nguyễn Thị Xuân Hoa là ai?", group:"05. Về người", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa"]} },
  { id:134, q:"PGS Nguyễn Bình Minh là ai?", group:"05. Về người", expect:"answer" },
  { id:135, q:"Giáo sư David Tran công tác ở đâu?", group:"05. Về người", expect:"answer", gold:{"text":["David Tran"]} },
  { id:136, q:"Hội đồng cố vấn có ai đến từ nước ngoài không?", group:"05. Về người", expect:"answer", gold:{"text":["David Tran"]} },
  { id:137, q:"Có giáo sư nào từ Singapore trong Hội đồng cố vấn không?", group:"05. Về người", expect:"answer", gold:{"text":["David Tran"]} },
  { id:138, q:"Ai phụ trách kế toán của Viện?", group:"05. Về người", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:139, q:"Ai là Chánh văn phòng của Viện?", group:"05. Về người", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:140, q:"Bộ phận đào tạo do ai phụ trách?", group:"05. Về người", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:141, q:"Các nhà nghiên cứu của Viện đến từ đâu?", group:"05. Về người", expect:"answer", gold:{"url":["about/researchers-and-assistants"]} },
  { id:142, q:"Viện có nghiên cứu viên nào từ SoICT không?", group:"05. Về người", expect:"answer" },
  { id:143, q:"Ai là người phụ trách phát triển kinh doanh?", group:"05. Về người", expect:"answer" },
  { id:144, q:"Thầy Lâm có những đóng góp gì cho Viện?", group:"05. Về người", expect:"answer", gold:{"text":["Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:145, q:"Ban lãnh đạo Viện gồm những ai?", group:"05. Về người", expect:"answer" },
  { id:146, q:"Ai đại diện Viện phát biểu tại hội thảo ECOTECH?", group:"05. Về người", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:147, q:"Diễn giả Hồ Tú Bảo nói về chủ đề gì?", group:"05. Về người", expect:"answer" },
  { id:148, q:"Ông Hoàng Nam Tiến tham gia sự kiện nào của Viện?", group:"05. Về người", expect:"answer" },
  { id:149, q:"Số điện thoại của Viện trưởng là gì?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:150, q:"Email cá nhân của thầy Đỗ Bá Lâm là gì?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:151, q:"Viện trưởng sinh năm bao nhiêu?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:152, q:"Thầy Nguyễn Bình Minh tốt nghiệp trường nào?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:153, q:"Lương của giảng viên tại Viện là bao nhiêu?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:154, q:"Ai sẽ là Viện trưởng nhiệm kỳ tới?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:155, q:"Địa chỉ nhà riêng của Viện trưởng ở đâu?", group:"05. Về người — corpus không có", expect:"not_updated" },
  { id:156, q:"Thầy đó là ai?", group:"05. Về người — mơ hồ", expect:"no_answer" },
  { id:157, q:"Anh ấy làm gì?", group:"05. Về người — mơ hồ", expect:"no_answer" },
  { id:158, q:"Cô ta có giỏi không?", group:"05. Về người — mơ hồ", expect:"no_answer" },
  { id:159, q:"Người đó tên gì?", group:"05. Về người — mơ hồ", expect:"no_answer" },
  { id:160, q:"Ai vậy?", group:"05. Về người — mơ hồ", expect:"no_answer" },
  { id:161, q:"vien truong bk fintech la ai", group:"06. Không dấu", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:162, q:"vien cong nghe va kinh te so la gi", group:"06. Không dấu", expect:"answer" },
  { id:163, q:"bk fintech co nhung khoa hoc nao", group:"06. Không dấu", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:164, q:"khoa business intelligence keo dai bao lau", group:"06. Không dấu", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:165, q:"khoa fintech hoc nhung gi", group:"06. Không dấu", expect:"answer" },
  { id:166, q:"vien co may phong lab", group:"06. Không dấu", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:167, q:"phong lab cua vien nghien cuu gi", group:"06. Không dấu", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:168, q:"v-chain la gi", group:"06. Không dấu", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:169, q:"vchain lam duoc gi", group:"06. Không dấu", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:170, q:"ediploma dung de lam gi", group:"06. Không dấu", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:171, q:"bksign la gi", group:"06. Không dấu", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:172, q:"bkoffice co tinh nang gi", group:"06. Không dấu", expect:"answer", gold:{"url":["solutions/BKOffice"],"text":["BKOffice"]} },
  { id:173, q:"du an cyber clinic la gi", group:"06. Không dấu", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:174, q:"cyber clinic keo dai bao lau", group:"06. Không dấu", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:175, q:"dieu kien tham gia cyber clinic", group:"06. Không dấu", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:176, q:"hoi thao ecotech ve chu de gi", group:"06. Không dấu", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:177, q:"hackday la cuoc thi gi", group:"06. Không dấu", expect:"answer", gold:{"text":["Hackday"]} },
  { id:178, q:"hackday to chuc lan thu may roi", group:"06. Không dấu", expect:"answer", gold:{"text":["Hackday"]} },
  { id:179, q:"bao cao kinh te so cua vien noi gi", group:"06. Không dấu", expect:"answer" },
  { id:180, q:"co so vat chat cua vien the nao", group:"06. Không dấu", expect:"answer" },
  { id:181, q:"dia chi cua vien o dau", group:"06. Không dấu", expect:"answer" },
  { id:182, q:"email lien he cua vien", group:"06. Không dấu", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:183, q:"lien he voi vien bang cach nao", group:"06. Không dấu", expect:"answer" },
  { id:184, q:"tam nhin cua vien la gi", group:"06. Không dấu", expect:"answer" },
  { id:185, q:"su menh cua vien", group:"06. Không dấu", expect:"answer" },
  { id:186, q:"ai la pho vien truong", group:"06. Không dấu", expect:"answer" },
  { id:187, q:"chu tich hoi dong co van la ai", group:"06. Không dấu", expect:"answer" },
  { id:188, q:"hoi dong vien gom nhung ai", group:"06. Không dấu", expect:"answer" },
  { id:189, q:"cac nha nghien cuu cua vien", group:"06. Không dấu", expect:"answer" },
  { id:190, q:"vien co hop tac voi doanh nghiep khong", group:"06. Không dấu", expect:"answer" },
  { id:191, q:"muon hop tac voi vien thi lam sao", group:"06. Không dấu", expect:"answer" },
  { id:192, q:"dang ky khoa hoc nhu the nao", group:"06. Không dấu", expect:"answer" },
  { id:193, q:"hoc phi bao nhieu", group:"06. Không dấu", expect:"answer" },
  { id:194, q:"vien co cap chung chi khong", group:"06. Không dấu", expect:"answer" },
  { id:195, q:"hoc xong duoc gi", group:"06. Không dấu", expect:"answer" },
  { id:196, q:"vien co tuyen thuc tap sinh khong", group:"06. Không dấu", expect:"answer" },
  { id:197, q:"sinh vien co tham gia duoc khong", group:"06. Không dấu", expect:"answer" },
  { id:198, q:"clb cua vien hoat dong the nao", group:"06. Không dấu", expect:"answer", gold:{"url":["get-involved/club"]} },
  { id:199, q:"workshop cua vien to chuc khi nao", group:"06. Không dấu", expect:"answer", gold:{"url":["get-involved/workshop-series"]} },
  { id:200, q:"vien thuoc truong nao", group:"06. Không dấu", expect:"answer" },
  { id:201, q:"What is BK Fintech?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:202, q:"What does the Institute for Digital Technology and Economy do?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["BKFintech|BK Fintech|Viện Công nghệ và Kinh tế số"]} },
  { id:203, q:"Which university is BK Fintech part of?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["Bách khoa|Hanoi University of Science"]} },
  { id:204, q:"What short courses does BK Fintech offer?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["/courses/"]} },
  { id:205, q:"How long is the Business Intelligence course?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:206, q:"What does the Business Intelligence course cover?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:207, q:"Who is the Dean of BK Fintech?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:208, q:"Who are the Vice-Deans?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:209, q:"Who chairs the Advisory Board?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["David Tran"]} },
  { id:210, q:"What research labs does the institute have?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:211, q:"What does the Smart Finance and Digital Banking Lab research?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["Smart Finance and Digital Banking"]} },
  { id:212, q:"What is V-Chain?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:213, q:"Which blockchain networks does V-Chain support?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:214, q:"What is eDiploma used for?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:215, q:"What is BKSign?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:216, q:"What problem does BKOffice solve?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["solutions/BKOffice"],"text":["BKOffice"]} },
  { id:217, q:"What is the Cyber Clinic project?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:218, q:"How long does the Cyber Clinic project run?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:219, q:"Who can join the Cyber Clinic programme?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:220, q:"What is the ECOTECH conference about?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:221, q:"What is BK Fintech Hackday?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["Hackday"]} },
  { id:222, q:"What is the Vietnam Digital Economy Review?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:223, q:"What certificates do learners receive after completing a course?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["certificate","chứng chỉ"]} },
  { id:224, q:"What facilities does the institute have?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["academic/facility"]} },
  { id:225, q:"How can I contact BK Fintech?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:226, q:"Where is the institute located?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:227, q:"What is the institute's vision?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["about/vision-and-operating-philosophy","about/welcome-message"]} },
  { id:228, q:"Does the institute collaborate with businesses?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:229, q:"How can a company partner with the institute?", group:"07. Tiếng Anh", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:230, q:"What is the Data Analysis course about?", group:"07. Tiếng Anh", expect:"answer", gold:{"url":["courses/data-analysis"]} },
  { id:231, q:"How much does the Business Intelligence course cost?", group:"07. Tiếng Anh — corpus không có", expect:"not_updated" },
  { id:232, q:"When does the next cohort start?", group:"07. Tiếng Anh — corpus không có", expect:"not_updated" },
  { id:233, q:"How many students study at the institute?", group:"07. Tiếng Anh — corpus không có", expect:"not_updated" },
  { id:234, q:"What is the acceptance rate?", group:"07. Tiếng Anh — corpus không có", expect:"not_updated" },
  { id:235, q:"What is the weather in Hanoi today?", group:"07. Tiếng Anh — ngoài phạm vi", expect:"nothing_found" },
  { id:236, q:"Doanh nghiệp có thể hợp tác với Viện như thế nào?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:237, q:"Viện có hợp tác với doanh nghiệp không?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:238, q:"Viện đã hợp tác với những doanh nghiệp nào?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:239, q:"Viện có ký kết hợp tác với ngân hàng nào chưa?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:240, q:"Hình thức hợp tác giữa Viện và doanh nghiệp là gì?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:241, q:"Viện có nhận đào tạo theo yêu cầu doanh nghiệp không?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:242, q:"Doanh nghiệp tham gia Cyber Clinic được lợi gì?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:243, q:"Viện có tổ chức đào tạo nội bộ cho công ty không?", group:"08. Doanh nghiệp hợp tác", expect:"not_updated" } /* "đào tạo nội bộ" không xuất hiện trong corpus */,
  { id:244, q:"Viện có thể tư vấn chuyển đổi số cho doanh nghiệp không?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:245, q:"Năng lực nghiên cứu của Viện trong lĩnh vực blockchain thế nào?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:246, q:"Viện có kinh nghiệm triển khai giải pháp ký số không?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:247, q:"BKSign đã được triển khai ở đâu chưa?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:248, q:"eDiploma đã có đơn vị nào sử dụng chưa?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:249, q:"Viện có tham gia tài trợ sự kiện không?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:250, q:"Doanh nghiệp có thể tài trợ cho Hackday không?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["Hackday"]} },
  { id:251, q:"Cơ hội tài trợ cho hội thảo ECOTECH là gì?", group:"08. Doanh nghiệp hợp tác", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:252, q:"Viện có chương trình kết nối doanh nghiệp với sinh viên không?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:253, q:"Làm sao để tuyển dụng sinh viên từ Viện?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:254, q:"Viện có hỗ trợ doanh nghiệp khởi nghiệp không?", group:"08. Doanh nghiệp hợp tác", expect:"answer" },
  { id:255, q:"Chi phí thuê Viện tư vấn là bao nhiêu?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:256, q:"Báo giá cho một dự án nghiên cứu chung là bao nhiêu?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:257, q:"Quy trình ký hợp đồng với Viện gồm mấy bước?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:258, q:"Mẫu hợp đồng hợp tác của Viện thế nào?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:259, q:"Điều khoản sở hữu trí tuệ khi hợp tác với Viện ra sao?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:260, q:"Thời gian trung bình để hoàn thành một dự án là bao lâu?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:261, q:"Viện có bảo hiểm trách nhiệm nghề nghiệp không?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:262, q:"Ai là đầu mối liên hệ cho hợp tác doanh nghiệp?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:263, q:"Số điện thoại phòng hợp tác doanh nghiệp là gì?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:264, q:"Viện có chính sách chiết khấu cho hợp đồng dài hạn không?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:265, q:"Viện có chứng chỉ ISO nào không?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:266, q:"Doanh nghiệp nước ngoài có hợp tác được không?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:267, q:"Viện có xuất hóa đơn VAT không?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:268, q:"Điều kiện thanh toán của Viện là gì?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:269, q:"Viện có ký NDA với đối tác không?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:270, q:"Tỷ lệ dự án hoàn thành đúng hạn của Viện là bao nhiêu?", group:"08. Doanh nghiệp — corpus không có", expect:"not_updated" },
  { id:271, q:"Tôi muốn đặt Viện làm một dự án thì liên hệ ai?", group:"09. Đặt dự án", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:272, q:"Tôi muốn hợp tác nghiên cứu, liên hệ thế nào?", group:"09. Đặt dự án", expect:"answer", gold:{"text":["fintech@hust\\.edu\\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:273, q:"Viện nhận làm dự án về AI không?", group:"09. Đặt dự án", expect:"answer" },
  { id:274, q:"Viện có làm dự án về blockchain không?", group:"09. Đặt dự án", expect:"answer" },
  { id:275, q:"Viện có làm phần mềm quản lý không?", group:"09. Đặt dự án", expect:"answer" },
  { id:276, q:"Tôi muốn đặt một dự án 500 triệu, quy trình thế nào?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:277, q:"Thời gian báo giá mất bao lâu?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:278, q:"Viện có nhận dự án gấp trong 1 tháng không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:279, q:"Tôi cần chuẩn bị hồ sơ gì để đề xuất dự án?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:280, q:"Viện có mẫu đề xuất dự án không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:281, q:"Ai sẽ là người quản lý dự án của tôi?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:282, q:"Viện có cam kết KPI cho dự án không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:283, q:"Nếu dự án chậm tiến độ thì xử lý thế nào?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:284, q:"Viện có nhận bảo trì sau khi bàn giao không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:285, q:"Chi phí bảo trì hàng năm là bao nhiêu?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:286, q:"Viện có đội ngũ bao nhiêu người cho một dự án?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:287, q:"Tôi có được chọn nhân sự tham gia dự án không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:288, q:"Viện có làm việc theo mô hình Agile không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:289, q:"Dự án sẽ bàn giao mã nguồn cho khách hàng chứ?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:290, q:"Viện có ký hợp đồng trọn gói không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:291, q:"Điều kiện nghiệm thu dự án là gì?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:292, q:"Viện có hỗ trợ triển khai lên hệ thống của chúng tôi không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:293, q:"Có thể ký hợp đồng khung nhiều năm không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:294, q:"Viện có kinh nghiệm làm việc với cơ quan nhà nước chưa?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:295, q:"Dự án có được bảo mật thông tin không?", group:"09. Đặt dự án — corpus không có", expect:"not_updated" },
  { id:296, q:"Khác biệt giữa lab SFDB và OE-Fin Lab là gì?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"text":["Smart Finance and Digital Banking"]} },
  { id:297, q:"Hackday và Hackathon của Viện khác nhau thế nào?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"text":["Hackday"]} },
  { id:298, q:"ECOTECH 2025 và ECOTECH 2026 khác gì nhau?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:299, q:"Business Intelligence và Business Intelligence AI-Powered Insights khác nhau ra sao?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:300, q:"Cyber Clinic khác gì so với các khóa đào tạo thông thường?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:301, q:"V-Chain khác gì với việc dùng trực tiếp Ethereum?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:302, q:"Vietnam Digital Economy Review 2024 và 2025 khác nhau chỗ nào?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:303, q:"Lab nào của Viện làm về hệ thống phi tập trung?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"text":["Decentralized Systems"]} },
  { id:304, q:"Nghiên cứu của Viện về AI tập trung vào hướng nào?", group:"10. Người có kinh nghiệm", expect:"answer" },
  { id:305, q:"Viện tiếp cận bài toán hiệu quả vận hành tài chính thế nào?", group:"10. Người có kinh nghiệm", expect:"answer" },
  { id:306, q:"Kiến trúc của V-Chain gồm những thành phần nào?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:307, q:"Smart contract trong V-Chain hoạt động ra sao?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:308, q:"Mô hình đào tạo của khóa Business Intelligence là gì?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:309, q:"Viện dùng công cụ nào để dạy phân tích dữ liệu?", group:"10. Người có kinh nghiệm", expect:"answer" },
  { id:310, q:"Chương trình Cyber Clinic chia thành mấy giai đoạn?", group:"10. Người có kinh nghiệm", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:311, q:"Viện dùng framework nào để phát triển BKSign?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:312, q:"V-Chain đạt throughput bao nhiêu giao dịch mỗi giây?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:313, q:"Viện có công bố mã nguồn mở nào không?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:314, q:"Bài báo nào của Viện được trích dẫn nhiều nhất?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:315, q:"Viện có patent nào chưa?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:316, q:"Chỉ số H-index của các nhà nghiên cứu là bao nhiêu?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:317, q:"Viện có hợp tác với trường nào ở châu Âu?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:318, q:"Ngân sách nghiên cứu của lab SFDB là bao nhiêu?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:319, q:"Roadmap phát triển V-Chain năm tới là gì?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:320, q:"Viện có kế hoạch mở ngành đào tạo chính quy không?", group:"10. Người có kinh nghiệm — corpus không có", expect:"not_updated" },
  { id:321, q:"thầy có những thành tích gì?", history:["Thầy Đỗ Bá Lâm là ai?"], group:"11. Nối tiếp — đại từ người", expect:"answer", gold:{"text":["Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:322, q:"thầy ấy phụ trách mảng nào?", history:["Viện trưởng của BK Fintech là ai?"], group:"11. Nối tiếp — đại từ người", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:323, q:"ông ấy công tác ở đâu?", history:["Chủ tịch Hội đồng cố vấn là ai?"], group:"11. Nối tiếp — đại từ người", expect:"answer", gold:{"text":["David Tran"]} },
  { id:324, q:"họ phụ trách gì?", history:["Phó Viện trưởng gồm những ai?"], group:"11. Nối tiếp — đại từ người", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:325, q:"cô ấy giữ chức vụ gì?", history:["Cô Nguyễn Thị Xuân Hoa là ai?"], group:"11. Nối tiếp — đại từ người", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa"]} },
  { id:326, q:"nó hỗ trợ những mạng nào?", history:["V-Chain là gì?"], group:"11. Nối tiếp — đại từ vật", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:327, q:"nó giải quyết vấn đề gì?", history:["V-Chain là gì?"], group:"11. Nối tiếp — đại từ vật", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:328, q:"nó dùng công nghệ gì?", history:["eDiploma là gì?"], group:"11. Nối tiếp — đại từ vật", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:329, q:"nó có gì khác các giải pháp khác?", history:["BKSign là gì?"], group:"11. Nối tiếp — đại từ vật", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:330, q:"nó dành cho ai?", history:["BKOffice là gì?"], group:"11. Nối tiếp — đại từ vật", expect:"answer", gold:{"url":["solutions/BKOffice"],"text":["BKOffice"]} },
  { id:331, q:"khóa đó học bao lâu?", history:["Khóa Business Intelligence dạy những gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"text":["30 hours","30 giờ"]} },
  { id:332, q:"khóa này dành cho ai?", history:["Khóa Fintech dạy gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:333, q:"cái Smart Finance thì nghiên cứu gì?", history:["Viện có những phòng lab nào?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"text":["Smart Finance and Digital Banking"]} },
  { id:334, q:"lab đó đặt ở đâu?", history:["Viện có những phòng lab nào?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:335, q:"kéo dài bao lâu?", history:["Dự án Cyber Clinic là gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:336, q:"ai được tham gia?", history:["Dự án Cyber Clinic là gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:337, q:"ai làm chủ tịch?", history:["Hội đồng cố vấn của Viện gồm những ai?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"text":["David Tran"]} },
  { id:338, q:"số mới nhất nói về gì?", history:["Vietnam Digital Economy Review là gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"text":["Chuyên san Khoa học Thường thức","D-Economy Review"]} },
  { id:339, q:"đã tổ chức mấy lần rồi?", history:["BK Fintech Hackday là gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"text":["Hackday"]} },
  { id:340, q:"năm nay chủ đề là gì?", history:["Hội thảo ECOTECH là gì?"], group:"11. Nối tiếp — chỉ định", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:341, q:"còn học phí?", history:["Khóa Business Intelligence học những gì?"], group:"11. Nối tiếp — lược ngữ hoàn toàn", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:342, q:"đăng ký thế nào?", history:["Viện có khóa học nào?"], group:"11. Nối tiếp — lược ngữ hoàn toàn", expect:"answer", gold:{"url":["/courses/"]} },
  { id:343, q:"điều kiện?", history:["Cyber Clinic là gì?"], group:"11. Nối tiếp — lược ngữ hoàn toàn", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:344, q:"còn eDiploma?", history:["V-Chain là gì?"], group:"11. Nối tiếp — lược ngữ hoàn toàn", expect:"answer", gold:{"url":["solutions/eDiploma"],"text":["eDiploma"]} },
  { id:345, q:"còn phó viện trưởng?", history:["Viện trưởng là ai?"], group:"11. Nối tiếp — lược ngữ hoàn toàn", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:346, q:"còn OE-Fin?", history:["Lab SFDB nghiên cứu gì?"], group:"11. Nối tiếp — lược ngữ hoàn toàn", expect:"answer", gold:{"text":["Operational Efficiency in Finance"]} },
  { id:347, q:"khóa đầu tiên dạy gì?", history:["BK Fintech là gì?","Viện có khóa học nào?"], group:"11. Nối tiếp — ba lượt", expect:"answer", gold:{"url":["/courses/"]} },
  { id:348, q:"còn lab kia?", history:["Viện có mấy lab?","lab Smart Finance làm gì?"], group:"11. Nối tiếp — ba lượt", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:349, q:"doanh nghiệp thì sao?", history:["Cyber Clinic là gì?","dành cho ai?"], group:"11. Nối tiếp — ba lượt", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:350, q:"chủ tịch là ai?", history:["Viện trưởng là ai?","còn hội đồng cố vấn?"], group:"11. Nối tiếp — ba lượt", expect:"answer", gold:{"text":["David Tran"]} },
  { id:351, q:"thế còn giá vàng hôm nay?", history:["Viện trưởng của BK Fintech là ai?"], group:"11. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:352, q:"à mà thời tiết Hà Nội thế nào?", history:["Viện có khóa học nào?"], group:"11. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:353, q:"Bitcoin giá bao nhiêu rồi?", history:["V-Chain là gì?"], group:"11. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:354, q:"khai giảng ngày nào?", history:["Khóa Business Intelligence dạy gì?"], group:"11. Nối tiếp — corpus không có", expect:"not_updated" },
  { id:355, q:"học phí từng khóa bao nhiêu?", history:["Viện có những khóa học nào?"], group:"11. Nối tiếp — corpus không có", expect:"not_updated" },
  { id:356, q:"chi phí tham gia bao nhiêu?", history:["Cyber Clinic là gì?"], group:"11. Nối tiếp — corpus không có", expect:"not_updated" },
  { id:357, q:"số điện thoại của thầy?", history:["Viện trưởng là ai?"], group:"11. Nối tiếp — corpus không có", expect:"not_updated" },
  { id:358, q:"cái đó thế nào?", history:["Viện có những khóa học nào?"], group:"11. Nối tiếp — mơ hồ sau ngữ cảnh rõ", expect:"no_answer" },
  { id:359, q:"còn cái kia?", history:["Viện có mấy lab?"], group:"11. Nối tiếp — mơ hồ sau ngữ cảnh rõ", expect:"no_answer" },
  { id:360, q:"thế à?", history:["V-Chain là gì?"], group:"11. Nối tiếp — mơ hồ sau ngữ cảnh rõ", expect:"no_answer" },
  { id:361, q:"cho tôi hỏi cái này với", group:"12. Mơ hồ", expect:"no_answer" },
  { id:362, q:"giúp tôi với", group:"12. Mơ hồ", expect:"no_answer" },
  { id:363, q:"thông tin", group:"12. Mơ hồ", expect:"no_answer" },
  { id:364, q:"cái đó là gì?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:365, q:"như thế nào?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:366, q:"bao nhiêu?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:367, q:"ở đâu?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:368, q:"khi nào?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:369, q:"ai?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:370, q:"tôi muốn hỏi", group:"12. Mơ hồ", expect:"no_answer" },
  { id:371, q:"alo", group:"12. Mơ hồ", expect:"no_answer" },
  { id:372, q:"hello", group:"12. Mơ hồ", expect:"no_answer" },
  { id:373, q:"cho hỏi tí", group:"12. Mơ hồ", expect:"no_answer" },
  { id:374, q:"bạn giúp được gì?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:375, q:"nói tiếp đi", group:"12. Mơ hồ", expect:"no_answer" },
  { id:376, q:"còn gì nữa không?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:377, q:"thế thôi à?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:378, q:"chi tiết hơn được không?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:379, q:"cụ thể là sao?", group:"12. Mơ hồ", expect:"no_answer" },
  { id:380, q:"ừ", group:"12. Mơ hồ", expect:"no_answer" },
  { id:381, q:"Giá vàng SJC hôm nay bao nhiêu một lượng?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:382, q:"Hướng dẫn tôi cách nấu phở bò ngon", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:383, q:"Đội tuyển Việt Nam đá với Thái Lan lúc mấy giờ?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:384, q:"Thời tiết Hà Nội ngày mai thế nào?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:385, q:"Cách chữa đau đầu tại nhà?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:386, q:"Phim nào đang chiếu rạp?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:387, q:"Bitcoin hôm nay giá bao nhiêu USD?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:388, q:"Lãi suất tiết kiệm Vietcombank kỳ hạn 12 tháng là bao nhiêu?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:389, q:"Cách triển khai một mô hình machine learning lên production?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:390, q:"So sánh React và Vue nên chọn cái nào?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:391, q:"Học Python bắt đầu từ đâu?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:392, q:"Blockchain hoạt động như thế nào?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:393, q:"Điểm chuẩn ngành Khoa học máy tính của Bách khoa Hà Nội năm nay?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:394, q:"Ký túc xá Bách khoa Hà Nội giá bao nhiêu một tháng?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:395, q:"Lịch thi cuối kỳ của Bách khoa khi nào?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:396, q:"BK Fintech có bán cà phê ở tầng 1 không?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:397, q:"Viện có tổ chức đám cưới không?", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:398, q:"Cho tôi số điện thoại của hiệu trưởng Bách khoa", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:399, q:"Viết giúp tôi một bài thơ về mùa thu", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:400, q:"Dịch câu này sang tiếng Nhật giúp tôi", group:"13. Ngoài phạm vi", expect:"nothing_found" },
  { id:401, q:"Khóa Business Intelligence khai giảng ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:402, q:"Khóa Fintech bắt đầu học từ ngày mấy?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:403, q:"Lớp Data Analysis mở vào thời gian nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:404, q:"Bao giờ khóa AI for Everyone khai giảng?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:405, q:"Ngày nhập học của khóa học tiếp theo là khi nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:406, q:"Hạn chót đăng ký khóa Business Intelligence là ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:407, q:"Khóa học kết thúc vào ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:408, q:"Lịch học cụ thể của khóa Fintech là thứ mấy hàng tuần?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:409, q:"Mỗi buổi học kéo dài từ mấy giờ đến mấy giờ?", group:"14. Bẫy ngày tháng", expect:"answer", gold:{"text":["7:00 PM"]} } /* KHÔNG phải bẫy: courses/business-intelligence-en ghi "Time: 7:00 PM – 9:00 PM on weekdays" */,
  { id:410, q:"Khóa học có học vào cuối tuần không?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:411, q:"Năm học mới của Viện bắt đầu khi nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:412, q:"Kỳ tuyển sinh tiếp theo mở vào tháng mấy?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:413, q:"Hạn nộp hồ sơ Cyber Clinic là ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:414, q:"Cyber Clinic khai giảng khóa mới vào ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:415, q:"ECOTECH 2026 tổ chức ngày nào?", group:"14. Bẫy ngày tháng", expect:"answer", gold:{"text":["03/6/2026|June 3, 2026"]} } /* KHÔNG phải bẫy: corpus ghi rõ ngày */,
  { id:416, q:"Hackday mùa tới diễn ra khi nào?", group:"14. Bẫy ngày tháng", expect:"answer", gold:{"text":["15/07 - 18/08/2026"]} } /* KHÔNG phải bẫy: get-involved/hackday ghi lịch Season 13 */,
  { id:417, q:"Workshop tiếp theo của Viện vào ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:418, q:"Báo cáo Vietnam Digital Economy Review 2026 phát hành khi nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:419, q:"Viện nghỉ Tết từ ngày nào đến ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:420, q:"Giờ làm việc của văn phòng Viện là mấy giờ?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:421, q:"Viện có làm việc thứ Bảy không?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:422, q:"Lịch tiếp khách của Viện trưởng là khi nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:423, q:"Thời gian nhận hồ sơ hợp tác là từ ngày nào?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:424, q:"Khi nào Viện công bố kết quả xét duyệt đề tài?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:425, q:"Buổi bảo vệ đề tài diễn ra ngày mấy?", group:"14. Bẫy ngày tháng", expect:"not_updated" },
  { id:426, q:"Viện có chứng chỉ ISO nào không?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:427, q:"Viện đạt chứng nhận ISO 9001 chưa?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:428, q:"Hệ thống quản lý chất lượng của Viện theo tiêu chuẩn nào?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:429, q:"Điều khoản sở hữu trí tuệ khi doanh nghiệp hợp tác với Viện là gì?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:430, q:"Ai sở hữu kết quả nghiên cứu sau khi hợp tác với Viện?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:431, q:"Viện có đăng ký bằng sáng chế nào chưa?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:432, q:"Số điện thoại liên hệ của Viện là gì?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:433, q:"Hotline hỗ trợ học viên là số nào?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:434, q:"Số fax của Viện là gì?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:435, q:"Chính sách bảo mật dữ liệu khách hàng của Viện thế nào?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:436, q:"Viện cam kết bảo mật thông tin dự án ra sao?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:437, q:"Viện có ký thỏa thuận bảo mật NDA không?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:438, q:"Mức lương khởi điểm khi làm việc tại Viện là bao nhiêu?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:439, q:"Viện tuyển dụng vị trí nào hiện nay?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:440, q:"Quy trình phỏng vấn vào Viện gồm mấy vòng?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:441, q:"Viện có chính sách nghỉ phép thế nào?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:442, q:"Bảo hiểm cho nhân viên Viện ra sao?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:443, q:"Viện có bao nhiêu phòng ban hành chính?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:444, q:"Cơ cấu tổ chức của Viện gồm những cấp nào?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:445, q:"Viện trực thuộc phòng ban nào của trường?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:446, q:"Ngân sách nghiên cứu hàng năm của Viện là bao nhiêu?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:447, q:"Nguồn tài trợ chính của Viện đến từ đâu?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:448, q:"Viện có quỹ đầu tư mạo hiểm không?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:449, q:"Viện có công ty con nào không?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:450, q:"Doanh thu từ chuyển giao công nghệ của Viện là bao nhiêu?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:451, q:"Viện có chi nhánh ở thành phố nào khác không?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:452, q:"Viện có văn phòng đại diện ở nước ngoài không?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:453, q:"Diện tích cơ sở vật chất của Viện là bao nhiêu mét vuông?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:454, q:"Viện có bao nhiêu máy chủ phục vụ nghiên cứu?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:455, q:"Viện dùng nền tảng đám mây nào?", group:"15. Bẫy thực thể gần giống", expect:"not_updated" },
  { id:456, q:"Tổng số giờ học của tất cả các khóa cộng lại là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:457, q:"Trung bình một khóa học của Viện kéo dài bao nhiêu giờ?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:458, q:"Khóa nào của Viện dài nhất và dài hơn khóa ngắn nhất bao nhiêu giờ?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:459, q:"Tỷ lệ học viên hoàn thành khóa học là bao nhiêu phần trăm?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:460, q:"Bao nhiêu phần trăm học viên có việc làm sau khóa học?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:461, q:"Số học viên trung bình mỗi khóa là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:462, q:"Viện đã đào tạo tổng cộng bao nhiêu người từ khi thành lập?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:463, q:"Tổng số thành viên của tất cả các hội đồng là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:464, q:"Tỷ lệ nam nữ trong đội ngũ của Viện là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:465, q:"Độ tuổi trung bình của các nhà nghiên cứu là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:466, q:"Bao nhiêu phần trăm nhân sự của Viện có bằng tiến sĩ?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:467, q:"Số bài báo khoa học trung bình mỗi năm của Viện là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:468, q:"Tổng giá trị các hợp đồng Viện đã ký là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:469, q:"Trung bình mỗi dự án của Viện kéo dài bao lâu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:470, q:"Viện đã tổ chức tổng cộng bao nhiêu sự kiện?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:471, q:"Tổng số người tham dự các hội thảo của Viện là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:472, q:"Số lượng đối tác của Viện tăng bao nhiêu phần trăm mỗi năm?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:473, q:"Hackday qua các mùa có tổng bao nhiêu đội tham gia?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:474, q:"Giải thưởng trung bình mỗi mùa Hackday là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:475, q:"Ngân sách cho mỗi phòng lab là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:476, q:"Lab nào của Viện có nhiều công bố nhất?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:477, q:"Giải pháp nào của Viện được triển khai nhiều nhất?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:478, q:"Khóa học nào của Viện đông học viên nhất?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:479, q:"Tỷ lệ dự án hoàn thành đúng hạn là bao nhiêu?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:480, q:"So với năm ngoái, số khóa học của Viện tăng hay giảm?", group:"16. Bẫy số liệu suy diễn", expect:"not_updated" },
  { id:481, q:"Tại sao học phí khóa Fintech lại đắt như vậy?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:482, q:"Vì sao Viện tăng học phí năm nay?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:483, q:"Khóa học 50 triệu của Viện gồm những gì?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:484, q:"Tại sao Viện chỉ nhận sinh viên Bách khoa?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:485, q:"Vì sao Viện không nhận học viên đã đi làm?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:486, q:"Tại sao Viện ngừng tổ chức Hackday?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:487, q:"Vì sao dự án Cyber Clinic bị hủy?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:488, q:"Tại sao Viện trưởng từ chức?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:489, q:"Vì sao Viện chuyển trụ sở sang cơ sở mới?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:490, q:"Tại sao V-Chain ngừng hoạt động?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:491, q:"Vì sao BKSign bị lỗi bảo mật năm ngoái?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:492, q:"Tại sao eDiploma chưa được Bộ công nhận?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:493, q:"Viện bị phạt vì vi phạm gì?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:494, q:"Tại sao Viện mất hợp đồng với Rikkeisoft?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:495, q:"Vì sao số lượng học viên của Viện giảm mạnh?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:496, q:"Tại sao ECOTECH 2026 bị hoãn?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:497, q:"Chi nhánh TP.HCM của Viện ở đâu?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:498, q:"Chương trình thạc sĩ của Viện học mấy năm?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:499, q:"Điểm chuẩn vào Viện năm nay là bao nhiêu?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:500, q:"Ký túc xá của Viện có mấy phòng?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:501, q:"Căng tin của Viện mở cửa mấy giờ?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:502, q:"Bãi gửi xe của Viện thu phí bao nhiêu?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:503, q:"App di động của Viện tải ở đâu?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:504, q:"Kênh YouTube của Viện có bao nhiêu người đăng ký?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:505, q:"Viện có bao nhiêu giải Nobel?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:506, q:"Tại sao Viện xếp hạng thấp hơn năm ngoái?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:507, q:"Đối thủ cạnh tranh lớn nhất của Viện là ai?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:508, q:"Viện có kế hoạch IPO khi nào?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:509, q:"Cổ đông lớn nhất của Viện là ai?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:510, q:"Viện lỗ bao nhiêu tiền năm 2025?", group:"17. Tiền đề sai", expect:"not_updated" },
  { id:511, q:"Ai giữ chức Viện trưởng?", group:"18. Về người — corpus có", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:512, q:"Những ai là Phó Viện trưởng?", group:"18. Về người — corpus có", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:513, q:"Chức danh của ông David Tran trong Hội đồng cố vấn là gì?", group:"18. Về người — corpus có", expect:"answer", gold:{"text":["David Tran"]} },
  { id:514, q:"Ai là Chủ tịch Hội đồng Viện?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/institute-council"]} },
  { id:515, q:"Ai là Phó Chủ tịch Hội đồng Viện?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/institute-council"]} },
  { id:516, q:"Kế toán trưởng của Viện là ai?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:517, q:"Ai làm Chánh văn phòng?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:518, q:"Những ai giữ chức Training Manager?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:519, q:"Ai phụ trách Business Development?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/back-office"]} },
  { id:520, q:"Hội đồng cố vấn có thành viên nào từ Anh không?", group:"18. Về người — corpus có", expect:"answer", gold:{"text":["David Tran"]} },
  { id:521, q:"Thành viên nào của Hội đồng cố vấn đến từ Mỹ?", group:"18. Về người — corpus có", expect:"answer", gold:{"text":["David Tran"]} },
  { id:522, q:"Ai là CEO của Republic trong Hội đồng cố vấn?", group:"18. Về người — corpus có", expect:"answer", gold:{"text":["David Tran"]} },
  { id:523, q:"Giáo sư Lim Kian Guan công tác tại đâu?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/advisory-board","about/institute-council"]} },
  { id:524, q:"Giáo sư Vũ Minh Khương làm việc ở trường nào?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/advisory-board","about/institute-council"]} },
  { id:525, q:"Nhà nghiên cứu nào của Viện đến từ FAMI?", group:"18. Về người — corpus có", expect:"answer", gold:{"url":["about/researchers-and-assistants"]} },
  { id:526, q:"Viện trưởng phụ trách những mảng công việc nào?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:527, q:"Phó Viện trưởng Xuân Hoa phụ trách lĩnh vực gì?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:528, q:"Thầy Đỗ Bá Lâm phụ trách mảng nào của Viện?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:529, q:"Ai chịu trách nhiệm về mảng đối ngoại của Viện?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:530, q:"Ai quản lý các phòng lab?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:531, q:"Người nào phụ trách tuyển sinh?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:532, q:"Ai là đầu mối cho doanh nghiệp muốn hợp tác?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:533, q:"Trưởng phòng nghiên cứu của Viện là ai?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:534, q:"Ai phụ trách truyền thông của Viện?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:535, q:"Người nào chịu trách nhiệm về chất lượng đào tạo?", group:"18. Về người — chỉ có chức danh, không có mảng phụ trách", expect:"not_updated" },
  { id:536, q:"ok", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:537, q:"vâng", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:538, q:"sao cơ?", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:539, q:"gì cơ", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:540, q:"không hiểu", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:541, q:"bạn nói gì vậy", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:542, q:"cái này", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:543, q:"cái kia thì sao", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:544, q:"vậy à", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:545, q:"thế nào ạ", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:546, q:"cho mình xin thông tin", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:547, q:"mình cần tư vấn", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:548, q:"giúp mình cái", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:549, q:"hỏi tí được không", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:550, q:"bạn có biết không", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:551, q:"nói rõ hơn đi", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:552, q:"còn nữa không", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:553, q:"tiếp đi", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:554, q:"xong chưa", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:555, q:"hết rồi à", group:"19. Mơ hồ mở rộng", expect:"no_answer" },
  { id:556, q:"còn giá xăng hôm nay?", history:["Khóa Business Intelligence dạy gì?"], group:"20. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:557, q:"à mà mấy giờ rồi?", history:["Viện trưởng là ai?"], group:"20. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:558, q:"cho tôi công thức nấu bún chả", history:["V-Chain là gì?"], group:"20. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:559, q:"đội Việt Nam thắng chưa?", history:["Cyber Clinic là gì?"], group:"20. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:560, q:"dịch giúp tôi câu này sang tiếng Trung", history:["Viện có mấy lab?"], group:"20. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:561, q:"kể tôi nghe một câu chuyện cười", history:["BKSign là gì?"], group:"20. Nối tiếp — đổi chủ đề ra ngoài", expect:"nothing_found" },
  { id:562, q:"thế hiệu trưởng Bách khoa là ai?", history:["Viện trưởng BK Fintech là ai?"], group:"20. Nối tiếp — đổi sang chủ thể khác", expect:"not_updated" },
  { id:563, q:"còn Đại học Kinh tế Quốc dân có không?", history:["Viện có khóa Business Intelligence không?"], group:"20. Nối tiếp — đổi sang chủ thể khác", expect:"not_updated" },
  { id:564, q:"còn VNG thì làm sản phẩm gì?", history:["V-Chain của Viện là gì?"], group:"20. Nối tiếp — đổi sang chủ thể khác", expect:"not_updated" },
  { id:565, q:"còn lab của FPT thì sao?", history:["Lab SFDB nghiên cứu gì?"], group:"20. Nối tiếp — đổi sang chủ thể khác", expect:"not_updated" },
  { id:566, q:"Rikkeisoft doanh thu bao nhiêu?", history:["Viện hợp tác với Rikkeisoft à?"], group:"20. Nối tiếp — đổi sang chủ thể khác", expect:"not_updated" },
  { id:567, q:"khóa 50 triệu kia học mấy tháng?", history:["Viện có những khóa học nào?"], group:"20. Nối tiếp — tiền đề sai cài trong lượt sau", expect:"not_updated" },
  { id:568, q:"sao thầy ấy nghỉ việc vậy?", history:["Viện trưởng là ai?"], group:"20. Nối tiếp — tiền đề sai cài trong lượt sau", expect:"not_updated" },
  { id:569, q:"vì sao dự án bị dừng?", history:["Cyber Clinic là gì?"], group:"20. Nối tiếp — tiền đề sai cài trong lượt sau", expect:"not_updated" },
  { id:570, q:"lab thứ tư tên gì?", history:["Viện có mấy lab?"], group:"20. Nối tiếp — tiền đề sai cài trong lượt sau", expect:"not_updated" },
  { id:571, q:"mùa 20 tổ chức khi nào?", history:["Hackday là gì?"], group:"20. Nối tiếp — tiền đề sai cài trong lượt sau", expect:"not_updated" },
  { id:572, q:"quay lại V-Chain, nó hỗ trợ mạng nào?", history:["V-Chain là gì?","thời tiết thế nào?"], group:"20. Nối tiếp — quay lại chủ đề cũ sau khi lạc", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:573, q:"thầy ấy tên đầy đủ là gì?", history:["Viện trưởng là ai?","mấy giờ rồi?"], group:"20. Nối tiếp — quay lại chủ đề cũ sau khi lạc", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:574, q:"khóa đó bao nhiêu giờ?", history:["Khóa Fintech dạy gì?","giá vàng bao nhiêu?"], group:"20. Nối tiếp — quay lại chủ đề cũ sau khi lạc", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:575, q:"dự án đó kéo dài bao lâu?", history:["Cyber Clinic là gì?","hôm nay thứ mấy?"], group:"20. Nối tiếp — quay lại chủ đề cũ sau khi lạc", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:576, q:"nó dùng công nghệ gì?", history:["Viện có V-Chain và eDiploma."], group:"20. Nối tiếp — đại từ trỏ sai/mơ hồ", expect:"no_answer" },
  { id:577, q:"cái đó nghiên cứu gì?", history:["Viện có 3 lab."], group:"20. Nối tiếp — đại từ trỏ sai/mơ hồ", expect:"no_answer" },
  { id:578, q:"ông ấy phụ trách gì?", history:["Ban giám đốc có 3 người."], group:"20. Nối tiếp — đại từ trỏ sai/mơ hồ", expect:"no_answer" },
  { id:579, q:"khóa đó bao nhiêu tiền?", history:["Viện có nhiều khóa học."], group:"20. Nối tiếp — đại từ trỏ sai/mơ hồ", expect:"no_answer" },
  { id:580, q:"ai cơ?", history:["Viện trưởng là ai?"], group:"20. Nối tiếp — hỏi lại chính câu vừa trả lời", expect:"answer", gold:{"text":["Nguyen Binh Minh|Nguyễn Bình Minh"]} },
  { id:581, q:"nhắc lại giúp tôi", history:["V-Chain là gì?"], group:"20. Nối tiếp — hỏi lại chính câu vừa trả lời", expect:"answer", gold:{"url":["solutions/V-Chain"],"text":["V-Chain"]} },
  { id:582, q:"mấy cái cơ?", history:["Viện có mấy lab?"], group:"20. Nối tiếp — hỏi lại chính câu vừa trả lời", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:583, q:"bao nhiêu giờ cơ?", history:["Khóa BI bao nhiêu giờ?"], group:"20. Nối tiếp — hỏi lại chính câu vừa trả lời", expect:"answer" },
  { id:584, q:"bao lâu cơ?", history:["Cyber Clinic kéo dài bao lâu?"], group:"20. Nối tiếp — hỏi lại chính câu vừa trả lời", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:585, q:"nói lại đi", history:["BKSign là gì?"], group:"20. Nối tiếp — hỏi lại chính câu vừa trả lời", expect:"answer", gold:{"url":["solutions/BKSign"],"text":["BKSign"]} },
  { id:586, q:"Học viên Cyber Clinic có được hỗ trợ chi phí không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:587, q:"Cyber Clinic có học bổng không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:588, q:"Học viên có được thực tập tại doanh nghiệp không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"text":["thực tập|On-the-Job|internship"]} },
  { id:589, q:"Học xong khóa học có được cấp chứng chỉ không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"text":["certificate","chứng chỉ"]} },
  { id:590, q:"Khóa Business Intelligence: AI-Powered Insights có mất phí không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:591, q:"Viện có hỗ trợ học viên tham gia hội thảo khoa học không?", group:"21. Corpus có — không được từ chối", expect:"answer" },
  { id:592, q:"Đối tác chính của Viện gồm những công ty nào?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:593, q:"Rikkeisoft hợp tác với Viện trong lĩnh vực gì?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"text":["partners|đối tác","Rikkeisoft"]} },
  { id:594, q:"Viện có chương trình đào tạo cho giảng viên không?", group:"21. Corpus có — không được từ chối", expect:"answer" },
  { id:595, q:"Doanh nghiệp tham gia Cyber Clinic nhận được gì?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:596, q:"Khóa Business Intelligence học ở địa điểm nào?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"url":["courses/business-intelligence"]} },
  { id:597, q:"Khóa học của Viện có hình thức online không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"url":["/courses/"]} },
  { id:598, q:"Viện có tổ chức Public Lecture không?", group:"21. Corpus có — không được từ chối", expect:"answer" },
  { id:599, q:"Nghiên cứu sinh tại Viện có được ký hợp đồng lao động không?", group:"21. Corpus có — không được từ chối", expect:"answer" },
  { id:600, q:"Viện có hỗ trợ đăng ký học bổng và trao đổi học thuật không?", group:"21. Corpus có — không được từ chối", expect:"answer", gold:{"text":["học bổng|scholarship"]} },

  // --- Bộ HỒI QUY gốc (trước là scripts/qa-cases.ts) --------------------
  // 16 câu này giữ NGUYÊN VĂN từ bộ 30 câu ban đầu — chúng đã được đo trước
  // và sau đợt port, nên đổi một chữ là mất đường cơ sở để so. 14 câu còn
  // lại của bộ đó đã trùng nội dung với phần trên nên không chép lại.
  { id:601, q:"BK Fintech có những khóa học ngắn hạn nào?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["/courses/"]} },
  { id:602, q:"Viện có những phòng lab nghiên cứu nào?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["r&d-labs/"]} },
  { id:603, q:"Tầm nhìn của viện là gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["about/vision-and-operating-philosophy"]} },
  { id:604, q:"Hội thảo ECOTECH 2026 có chủ đề gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"text":["ECOTECH"]} },
  { id:605, q:"Chương trình trải nghiệm ngành IT cho học sinh THPT có mục tiêu gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["level-up-it"]} },
  { id:606, q:"Viện Công nghệ và Kinh tế số được thành lập vào năm nào?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"not_updated" },
  { id:607, q:"Phó Viện trưởng của BK Fintech gồm những ai?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"text":["Xuan Hoa|Xuân Hoa","Do Ba Lam|Đỗ Bá Lâm"]} },
  { id:608, q:"BKOffice dùng để làm gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["solutions/BKOffice"],"text":["BKOffice"]} },
  { id:609, q:"Phòng lab Smart Finance and Digital Banking nghiên cứu về lĩnh vực gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"text":["Smart Finance and Digital Banking"]} },
  { id:610, q:"Dự án Cyber Clinic kéo dài trong bao lâu?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"text":["15 months","15 tháng"]} },
  { id:611, q:"Điều kiện để học viên tham gia dự án Cyber Clinic là gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["cyber-clinic"],"text":["Cyber Clinic"]} },
  { id:612, q:"Khóa học Fintech kéo dài bao nhiêu giờ?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["courses/fintech-course"]} },
  { id:613, q:"Cơ sở vật chất phục vụ học tập của Viện như thế nào?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"url":["academic/facility"]} },
  { id:614, q:"Email và địa chỉ liên hệ của BK Fintech là gì?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"answer", gold:{"text":["fintech@hust\.edu\.vn","Tạ Quang Bửu|Ta Quang Buu"]} },
  { id:615, q:"Học phí khóa học Fintech là bao nhiêu?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"not_updated" },
  { id:616, q:"Khóa Business Intelligence khai giảng vào ngày nào?", group:"00. Hồi quy (bộ gốc, từ ngữ bất biến)", expect:"not_updated" },
];

export const GROUPS: string[] = [...new Set(SAMPLES.map((c) => c.group))];

/** Một chunk có chứa đáp án không. Khớp `text` HOẶC `url` là đủ. */
export function isGold(
  chunk: { url?: string; raw?: string; content?: string },
  gold: Gold
): boolean {
  if (gold.url?.some((u) => (chunk.url || "").includes(u))) return true;
  if (!gold.text?.length) return false;
  const hay = chunk.raw || chunk.content || "";
  return gold.text.some((t) => new RegExp(t, "i").test(hay));
}
