/**
 * 10 câu hỏi tiếng Việt thật, mỗi câu 950–1000 ký tự — tức sát trần
 * MAX_QUESTION_CHARS mới. Dùng để đo RAM ở đúng ca xấu nhất mà API còn cho qua
 * sau khi hạ giới hạn từ 2000 xuống 1000.
 *
 * Bộ này KHÔNG thay thế questions-250w.ts (~1246 ký tự, trần cũ). Giữ cả hai để
 * so sánh ngược được giữa hai ngưỡng bất cứ lúc nào — nếu ghi đè bộ cũ thì số
 * đo cũ mất chỗ dựa và không còn kiểm chứng lại được.
 *
 * Nội dung cố ý trải rộng chủ đề (khóa ngắn hạn, học phí, chương trình, nghiên
 * cứu, thực tập, cao học, hợp tác quốc tế, dữ liệu, sự kiện, chuyển đổi số):
 * 10 câu na ná nhau sẽ cho bản dịch có độ dài đầu ra gần giống nhau, và chi phí
 * beam search của model dịch phụ thuộc vào chính độ dài đó — đo như vậy sẽ ra
 * một con số hẹp hơn thực tế.
 */

export const QUESTIONS: string[] = [
  // 1 — khóa học ngắn hạn cho người đi làm
  `Tôi hiện đang làm chuyên viên phân tích tại một công ty chứng khoán ở Hà Nội, công việc hằng ngày chủ yếu xoay quanh việc tổng hợp số liệu và lập báo cáo bằng Excel. Gần đây công ty tôi bắt đầu triển khai một số hệ thống tự động hóa và tôi nhận thấy nếu không bổ sung kiến thức về dữ liệu thì sẽ rất khó theo kịp công việc trong vài năm tới. Tôi muốn hỏi viện có tổ chức các khóa học ngắn hạn dành riêng cho người đã đi làm hay không, nội dung mỗi khóa gồm những phần nào và thường kéo dài bao lâu. Lịch học được sắp xếp vào buổi tối trong tuần hay cuối tuần, và có hình thức học trực tuyến cho người bận rộn không? Học phí mỗi khóa khoảng bao nhiêu, có giảm giá khi đăng ký theo nhóm từ cùng một công ty không? Sau khi hoàn thành thì học viên nhận được chứng chỉ gì? Tôi cũng muốn biết đầu vào có yêu cầu nền tảng lập trình hay toán học ở mức nào không, vì tôi đã khá lâu rồi không đụng đến những thứ đó và hơi e ngại mình sẽ không theo kịp lớp. Mong anh chị tư vấn giúp tôi lộ trình phù hợp.`,

  // 2 — học phí và các khoản chi phí
  `Con tôi vừa nhận được kết quả trúng tuyển và gia đình đang phải tính toán lại toàn bộ chi phí cho bốn năm học sắp tới, vì nhà tôi còn một cháu nhỏ nữa cũng đang đi học nên ngân sách khá eo hẹp. Tôi muốn hỏi mức học phí hiện nay của viện là bao nhiêu cho một học kỳ, hay nếu tính theo tín chỉ thì mỗi tín chỉ giá bao nhiêu và một năm sinh viên thường đăng ký khoảng bao nhiêu tín chỉ? Học phí giữa chương trình đại trà và chương trình chất lượng cao có chênh lệch nhiều không? Điều tôi lo nhất là học phí có tăng theo từng năm hay không, nếu có thì mức tăng hằng năm vào khoảng bao nhiêu phần trăm, bởi tôi cần dự trù cho cả bốn năm chứ không riêng năm đầu. Ngoài học phí chính thức thì gia đình còn phải chuẩn bị những khoản nào khác, chẳng hạn phí ký túc xá, phí thực hành, tài liệu hay bảo hiểm y tế? Viện có chính sách miễn giảm cho sinh viên hoàn cảnh khó khăn không và thủ tục xin miễn giảm cần những giấy tờ gì, nộp vào lúc nào? Rất mong sớm nhận được phản hồi từ nhà trường.`,

  // 3 — chương trình đào tạo và hướng chuyên sâu
  `Em là sinh viên năm nhất và em muốn lên kế hoạch học tập cho cả quãng đại học ngay từ bây giờ, tránh trường hợp đến năm ba mới phát hiện mình chọn sai hướng rồi phải học lại nhiều môn. Em muốn hỏi chương trình đào tạo của viện kéo dài mấy năm và tổng cộng bao nhiêu tín chỉ, trong đó khối đại cương chiếm bao nhiêu, cơ sở ngành bao nhiêu và chuyên ngành bao nhiêu? Trong hai năm đầu sinh viên sẽ học chủ yếu những môn gì, và từ năm thứ ba thì có được tự chọn hướng chuyên sâu không, nếu có thì hiện có những hướng nào để lựa chọn? Em nghe nói viện đào tạo liên ngành, kết hợp công nghệ thông tin với tài chính và kinh tế, vậy tỷ trọng giữa các khối kiến thức đó phân bổ ra sao, và một sinh viên vốn không mạnh về kinh tế thì có theo được không? Chương trình có bao nhiêu môn giảng dạy bằng tiếng Anh, chuẩn đầu ra ngoại ngữ yêu cầu ở mức nào, và thực tập doanh nghiệp có phải là học phần bắt buộc hay không ạ? Ngoài ra đồ án tốt nghiệp được thực hiện trong bao nhiêu tuần ạ?`,

  // 4 — nghiên cứu và hợp tác học thuật
  `Tôi là giảng viên tại một trường đại học ở khu vực miền Trung, hiện đang tìm cơ hội hợp tác nghiên cứu trong lĩnh vực công nghệ tài chính và kinh tế số nên rất muốn tìm hiểu kỹ hơn về hoạt động khoa học của viện. Tôi muốn hỏi viện đang có những nhóm nghiên cứu hay phòng thí nghiệm nào hoạt động, mỗi nhóm theo đuổi hướng cụ thể nào và do thầy cô nào phụ trách? Trong vài năm gần đây viện đã công bố khoảng bao nhiêu bài báo khoa học, và các công bố đó chủ yếu đăng ở những tạp chí hay hội nghị nào, có thuộc danh mục ISI hoặc Scopus không? Viện hiện có chủ trì hay tham gia đề tài cấp nhà nước, cấp bộ hoặc dự án hợp tác quốc tế nào không, quy mô và thời gian thực hiện ra sao? Nếu đơn vị tôi muốn đề xuất hợp tác nghiên cứu thì quy trình bắt đầu từ đâu và cần liên hệ bộ phận nào? Ngoài ra viện có tổ chức hội thảo thường niên hay seminar chuyên đề mở cho người ngoài tham dự không, và thường vào thời gian nào trong năm? Rất mong nhận được thông tin chi tiết từ phía viện.`,

  // 5 — thực tập và kết nối doanh nghiệp
  `Em đang học năm ba và học kỳ tới em sẽ phải đăng ký thực tập, nhưng thú thật là em vẫn còn khá mơ hồ về việc mình nên chuẩn bị những gì từ bây giờ để không bị động khi đến lúc nộp hồ sơ. Em muốn hỏi viện tổ chức thực tập cho sinh viên theo hình thức nào, là viện chủ động giới thiệu sinh viên tới các doanh nghiệp đối tác hay sinh viên phải tự liên hệ và tự tìm chỗ thực tập? Nếu viện có danh sách doanh nghiệp đối tác thì hiện gồm những đơn vị nào, chủ yếu là ngân hàng, công ty chứng khoán hay công ty công nghệ? Kỳ thực tập kéo dài bao nhiêu tuần, diễn ra vào học kỳ nào và sinh viên có được trả lương hay phụ cấp trong thời gian đó không? Kết quả thực tập được đánh giá dựa trên tiêu chí gì, do người hướng dẫn ở doanh nghiệp chấm hay do giảng viên chấm? Em cũng muốn biết trước khi đi thực tập em nên trang bị thêm những kỹ năng hay công cụ nào để làm việc được ngay ạ? Nếu được thì anh chị cho em xin đầu mối liên hệ của bộ phận phụ trách thực tập để em chủ động hỏi thêm ạ.`,

  // 6 — cao học và học tiếp sau đại học
  `Tôi tốt nghiệp cử nhân kinh tế cách đây khoảng bảy năm và hiện đang làm việc trong bộ phận vận hành của một ngân hàng thương mại. Sau một thời gian đi làm tôi nhận ra mình cần học thêm ở bậc cao hơn để chuyển sang mảng phân tích dữ liệu và công nghệ tài chính, nên tôi rất quan tâm đến các chương trình sau đại học của viện. Tôi muốn hỏi viện hiện có đào tạo trình độ thạc sĩ hay tiến sĩ trong lĩnh vực này không, và nếu có thì tên chương trình cụ thể là gì, thời gian đào tạo kéo dài bao lâu? Điều kiện dự tuyển yêu cầu bằng cấp và ngành học đầu vào như thế nào, người tốt nghiệp ngành kinh tế như tôi có phải học bổ sung kiến thức không và nếu có thì khoảng bao nhiêu tín chỉ? Hình thức tuyển sinh là xét tuyển hồ sơ hay phải thi đầu vào, và yêu cầu chứng chỉ ngoại ngữ ở mức nào? Lịch học của bậc cao học có phù hợp với người vừa đi làm vừa học hay không ạ? Nếu có thể, xin cho tôi biết thêm thời gian nhận hồ sơ dự tuyển hằng năm rơi vào khoảng tháng mấy và học phí mỗi kỳ ra sao.`,

  // 7 — hợp tác quốc tế và trao đổi sinh viên
  `Em đang là sinh viên năm hai và một trong những lý do khiến em chọn viện là vì em nghe nói ở đây có nhiều cơ hội học tập và trao đổi với nước ngoài, nhưng đến giờ em vẫn chưa tìm được thông tin nào đầy đủ về chuyện này. Em muốn hỏi viện hiện đang hợp tác với những trường đại học hay tổ chức nào ở nước ngoài, và các chương trình hợp tác đó cụ thể là gì, có phải chương trình liên kết đào tạo cấp bằng đôi hay chỉ dừng ở mức trao đổi sinh viên ngắn hạn? Nếu có chương trình trao đổi thì mỗi năm viện cử đi khoảng bao nhiêu sinh viên, tiêu chí xét chọn dựa trên điểm trung bình, trình độ ngoại ngữ hay hoạt động ngoại khóa? Sinh viên đi trao đổi thì học phí đóng cho trường nào và chi phí sinh hoạt bên đó có được hỗ trợ phần nào không? Tín chỉ tích lũy ở trường bạn khi về nước có được công nhận đầy đủ hay em sẽ phải học lại một số môn ạ? Em cũng muốn biết trình độ tiếng Anh tối thiểu cần đạt là bao nhiêu và em nên chuẩn bị hồ sơ từ trước bao lâu để kịp nộp đúng đợt ạ.`,

  // 8 — kỹ năng dữ liệu và công cụ được học
  `Em vừa thi đỗ vào viện và trong lúc chờ nhập học em muốn tự học trước một chút để đỡ bỡ ngỡ, nhưng em không biết nên bắt đầu từ đâu vì trên mạng có quá nhiều nguồn và mỗi nơi lại khuyên một kiểu khác nhau. Em muốn hỏi trong chương trình học của viện thì sinh viên sẽ được học những ngôn ngữ lập trình nào, có phải chủ yếu là Python không hay còn học thêm những ngôn ngữ khác như Java, R hoặc SQL? Về mảng dữ liệu thì các môn học đi tới mức nào, chỉ dừng ở phân tích thống kê cơ bản hay có cả học máy và trí tuệ nhân tạo? Sinh viên có được thực hành trên dữ liệu thật của doanh nghiệp không hay chủ yếu làm trên bộ dữ liệu mẫu? Viện có dạy các công cụ mà doanh nghiệp đang dùng phổ biến như Power BI, Tableau hay các nền tảng đám mây không? Và nếu em muốn tự học trước trong ba tháng hè này thì thầy cô khuyên em nên bắt đầu với phần nào trước ạ? Em cũng băn khoăn không biết máy tính cá nhân của em cấu hình tầm trung thì có đủ để chạy các bài thực hành trên lớp hay không ạ.`,

  // 9 — sự kiện, câu lạc bộ và đời sống sinh viên
  `Em sắp trở thành sinh viên năm nhất và ngoài chuyện học hành thì em cũng rất muốn biết đời sống ở viện diễn ra như thế nào, vì em nghĩ bốn năm đại học không nên chỉ có mỗi việc lên lớp rồi về nhà. Em muốn hỏi viện và trường có những câu lạc bộ nào cho sinh viên tham gia, có câu lạc bộ nào liên quan trực tiếp đến chuyên môn như lập trình, phân tích dữ liệu hay khởi nghiệp không? Hằng năm viện tổ chức những sự kiện lớn nào cho sinh viên, chẳng hạn cuộc thi học thuật, hackathon, ngày hội việc làm hay hội thảo có diễn giả từ doanh nghiệp? Sinh viên năm nhất có được tham gia ngay từ đầu hay phải chờ đến năm hai? Em cũng muốn biết viện có các hoạt động kết nối giữa sinh viên các khóa với nhau và với cựu sinh viên không, vì em nghĩ học hỏi từ các anh chị đi trước sẽ giúp em định hướng tốt hơn rất nhiều ạ. À em còn muốn hỏi thêm là các câu lạc bộ đó sinh hoạt vào thời gian nào trong tuần, và việc tham gia có ảnh hưởng nhiều đến thời gian học trên lớp không ạ?`,

  // 10 — chuyển đổi số cho doanh nghiệp
  `Chúng tôi là một doanh nghiệp sản xuất quy mô vừa ở Bắc Ninh, hiện có khoảng ba trăm nhân sự và phần lớn quy trình quản lý vẫn đang làm thủ công trên giấy tờ và bảng tính. Ban giám đốc đã quyết định phải chuyển đổi số trong hai năm tới nhưng nội bộ chúng tôi chưa có ai đủ chuyên môn để dẫn dắt việc này nên đang tìm một đơn vị tư vấn đồng hành. Tôi muốn hỏi viện có nhận tư vấn hoặc triển khai chuyển đổi số cho doanh nghiệp bên ngoài hay không, và nếu có thì phạm vi công việc thường bao gồm những gì, từ khảo sát hiện trạng, xây dựng lộ trình cho tới triển khai hệ thống thực tế? Viện đã từng làm việc với những doanh nghiệp nào trong lĩnh vực sản xuất chưa và quy mô các dự án đó ra sao? Chi phí cho một dự án tư vấn thường được tính theo cách nào và kéo dài bao lâu? Ngoài ra viện có nhận đào tạo nội bộ cho đội ngũ nhân sự của chúng tôi không? Chúng tôi cũng muốn biết viện có thể cử chuyên gia xuống làm việc trực tiếp tại nhà máy của chúng tôi hay không.`,
]
