/**
 * 10 câu hỏi tiếng Việt dài (~250-290 từ) dùng chung cho các script đo RAM.
 * Tách ra file riêng để measure-ram-10q.ts và measure-ram-10q-split.ts đo trên
 * cùng một bộ dữ liệu — nếu mỗi script giữ bản sao riêng thì hai kết quả sẽ
 * không còn so sánh được với nhau khi ai đó sửa một bên.
 */
// 10 câu hỏi ~250 từ, kiểu người dùng thật viết dài dòng: nhiều mệnh đề phụ,
// nhiều câu hỏi phụ lồng trong một tin nhắn. Chủ đề trải rộng để bản dịch và
// vector truy vấn không trùng nhau giữa các câu.
export const QUESTIONS: string[] = [
  // 1 — tuyển sinh
  `Chào anh chị, em là học sinh lớp 12 ở Hà Nội và em đang rất phân vân trong việc chọn ngành cho kỳ tuyển sinh sắp tới. Em có tìm hiểu trên mạng và thấy Viện Công nghệ và Kinh tế số BK Fintech có vẻ là một hướng đi khá mới mẻ và thú vị, nhưng thú thật là em vẫn chưa hiểu rõ lắm về viện. Em muốn hỏi là viện hiện đang tuyển sinh những ngành nào, và mỗi ngành thì chỉ tiêu khoảng bao nhiêu sinh viên mỗi năm ạ? Điểm chuẩn của các năm trước là bao nhiêu, và viện có xét tuyển bằng các phương thức khác ngoài điểm thi tốt nghiệp trung học phổ thông không, ví dụ như xét học bạ, xét chứng chỉ tiếng Anh quốc tế như IELTS hay TOEFL, hoặc kết quả kỳ thi đánh giá tư duy của Đại học Bách khoa Hà Nội? Em có chứng chỉ IELTS 7.0 và học lực khá tốt các môn tự nhiên, đặc biệt là Toán và Tin học, nên em muốn biết liệu những điều đó có mang lại lợi thế gì trong quá trình xét tuyển hay không. Ngoài ra em cũng muốn hỏi thêm là hồ sơ đăng ký gồm những giấy tờ gì, thời hạn nộp hồ sơ vào khoảng tháng mấy, và em có cần phải tham gia phỏng vấn hay bài kiểm tra đầu vào nào riêng của viện nữa không ạ? Nếu được thì anh chị cho em xin thông tin liên hệ của bộ phận tuyển sinh để em tiện hỏi thêm những thắc mắc chi tiết hơn. Em xin chân thành cảm ơn anh chị rất nhiều ạ.`,

  // 2 — học phí và chi phí
  `Tôi là phụ huynh của một cháu đang chuẩn bị nộp hồ sơ vào viện, và điều tôi quan tâm nhất lúc này là vấn đề tài chính, bởi vì gia đình tôi thu nhập ở mức trung bình và cháu còn một em nhỏ đang đi học nữa. Tôi muốn hỏi cụ thể mức học phí của viện hiện nay là bao nhiêu một kỳ, hay tính theo tín chỉ thì mỗi tín chỉ giá bao nhiêu, và một năm học thì trung bình sinh viên phải đóng khoảng bao nhiêu tiền tất cả. Học phí có khác nhau giữa các ngành hay giữa chương trình đại trà và chương trình chất lượng cao, chương trình tiên tiến hay không? Một điều nữa tôi rất muốn biết là học phí có tăng theo từng năm không, và nếu có thì mức tăng hằng năm thường vào khoảng bao nhiêu phần trăm, bởi vì tôi cần tính toán trước cho cả bốn hoặc năm năm học của cháu chứ không chỉ năm đầu tiên. Ngoài học phí chính thức thì còn những khoản nào khác mà gia đình cần chuẩn bị nữa, chẳng hạn phí ký túc xá, phí thực hành thí nghiệm, phí tài liệu, bảo hiểm y tế hay các khoản thu đầu năm. Viện có chính sách miễn giảm học phí cho sinh viên có hoàn cảnh khó khăn, con em gia đình chính sách hay hộ nghèo không, và thủ tục xin miễn giảm thì cần những giấy tờ gì, nộp ở đâu và vào thời điểm nào trong năm học? Rất mong nhận được câu trả lời chi tiết. Tôi xin cảm ơn.`,

  // 3 — chương trình đào tạo
  `Em đang là sinh viên năm nhất và em muốn tìm hiểu thật kỹ về chương trình đào tạo của viện để có thể lên kế hoạch học tập cho cả quãng thời gian đại học sắp tới, tránh trường hợp học đến năm ba mới nhận ra mình đi sai hướng. Em muốn hỏi chương trình đào tạo của viện kéo dài bao nhiêu năm và tổng cộng bao nhiêu tín chỉ, trong đó phần đại cương chiếm bao nhiêu, phần cơ sở ngành bao nhiêu và phần chuyên ngành bao nhiêu tín chỉ? Cụ thể thì trong hai năm đầu sinh viên sẽ học những môn gì, và từ năm thứ ba trở đi thì có được tự chọn hướng chuyên sâu hay không, nếu có thì có những hướng nào để lựa chọn? Em nghe nói viện đào tạo theo hướng liên ngành, kết hợp giữa công nghệ thông tin, tài chính và kinh tế, vậy tỷ trọng giữa các khối kiến thức đó được phân bổ như thế nào, và liệu một sinh viên không mạnh về kinh tế có theo được không? Chương trình có bao nhiêu môn học bằng tiếng Anh, và có yêu cầu chuẩn đầu ra ngoại ngữ ở mức nào để được xét tốt nghiệp? Ngoài ra em cũng muốn biết viện có yêu cầu thực tập doanh nghiệp bắt buộc không, thực tập vào học kỳ nào và kéo dài bao lâu, và đồ án tốt nghiệp thì được thực hiện trong bao nhiêu tuần. Em rất mong nhận được thông tin đầy đủ để chuẩn bị tốt hơn. Em cảm ơn ạ.`,

  // 4 — blockchain
  `Tôi đang làm việc trong lĩnh vực ngân hàng được khoảng năm năm và gần đây tôi thấy các ngân hàng nơi tôi làm bắt đầu nói nhiều đến blockchain, tài sản số và hợp đồng thông minh, nhưng bản thân tôi lại chưa có nền tảng kỹ thuật vững nên khá lúng túng. Tôi muốn hỏi viện có đào tạo hay giảng dạy nội dung nào liên quan trực tiếp đến công nghệ blockchain hay không, và nếu có thì nó nằm trong chương trình chính quy dành cho sinh viên hay là một khóa học ngắn hạn riêng dành cho người đi làm như tôi? Nội dung học cụ thể gồm những gì, có đi vào các nền tảng phổ biến như Ethereum, Hyperledger hay Solana không, và sinh viên có thực sự viết được hợp đồng thông minh bằng Solidity sau khi học xong hay chỉ dừng ở mức lý thuyết tổng quan? Viện có phòng thí nghiệm hay nhóm nghiên cứu nào chuyên sâu về mảng này không, và các nghiên cứu đó đang tập trung vào hướng nào, chẳng hạn thanh toán xuyên biên giới, định danh số, tài chính phi tập trung hay truy xuất nguồn gốc hàng hóa? Tôi cũng quan tâm đến việc viện có hợp tác với ngân hàng hay công ty công nghệ tài chính nào để triển khai thử nghiệm thực tế hay không, vì tôi nghĩ học mà không gắn với bài toán thật thì rất khó ứng dụng. Nếu có khóa học phù hợp cho người đã đi làm thì lịch học vào buổi tối hay cuối tuần, học phí bao nhiêu và cấp chứng chỉ gì? Mong được tư vấn cụ thể.`,

  // 5 — giảng viên
  `Em chào anh chị, em đang cân nhắc giữa việc nộp hồ sơ vào viện và một trường khác, và một trong những tiêu chí quan trọng nhất với em là chất lượng đội ngũ giảng viên, bởi vì em nghĩ người dạy quyết định rất lớn đến việc mình học được gì trong bốn năm. Em muốn hỏi hiện tại viện có bao nhiêu giảng viên cơ hữu, trong đó bao nhiêu người có học vị tiến sĩ và bao nhiêu người có chức danh phó giáo sư hoặc giáo sư ạ? Các thầy cô chủ yếu được đào tạo ở đâu, trong nước hay nước ngoài, và nếu ở nước ngoài thì thường là những quốc gia nào? Em cũng muốn biết ban lãnh đạo của viện gồm những ai, viện trưởng và các phó viện trưởng là những thầy cô nào, chuyên môn của các thầy cô đó là gì và đã công tác trong lĩnh vực này bao lâu rồi? Ngoài giảng viên cơ hữu thì viện có mời thêm chuyên gia từ doanh nghiệp, ngân hàng hay các công ty công nghệ tài chính về giảng dạy hoặc chia sẻ không, và tỷ lệ những buổi học có người từ doanh nghiệp tham gia là khoảng bao nhiêu? Một điều nữa em rất quan tâm là các thầy cô có nhận sinh viên đại học vào nhóm nghiên cứu của mình không, và nếu em muốn tham gia nghiên cứu khoa học từ năm hai hay năm ba thì em nên liên hệ với ai và cần chuẩn bị những gì? Em xin cảm ơn anh chị đã dành thời gian đọc và trả lời ạ.`,

  // 6 — nghiên cứu
  `Tôi hiện là giảng viên tại một trường đại học ở khu vực miền Trung và tôi đang tìm kiếm cơ hội hợp tác nghiên cứu trong lĩnh vực công nghệ tài chính cũng như kinh tế số, nên tôi rất muốn tìm hiểu sâu hơn về hoạt động khoa học của viện. Tôi muốn hỏi viện hiện có những nhóm nghiên cứu hay phòng thí nghiệm nào đang hoạt động, mỗi nhóm tập trung vào hướng nghiên cứu cụ thể nào và do thầy cô nào phụ trách? Trong vài năm gần đây viện đã công bố khoảng bao nhiêu bài báo khoa học, và các công bố đó chủ yếu đăng trên những tạp chí hay hội nghị nào, có thuộc danh mục ISI hay Scopus không? Viện có đang chủ trì hoặc tham gia các đề tài nghiên cứu cấp nhà nước, cấp bộ hay các dự án hợp tác quốc tế nào không, và quy mô cũng như thời gian thực hiện của những đề tài đó ra sao? Tôi cũng muốn biết viện có sẵn sàng ký kết hợp tác nghiên cứu với các đơn vị bên ngoài hay không, quy trình đề xuất hợp tác thì bắt đầu từ đâu và cần liên hệ với bộ phận nào? Ngoài ra, viện có tổ chức hội thảo khoa học thường niên hay các buổi seminar chuyên đề mở cho người ngoài tham dự không, và nếu có thì thường diễn ra vào thời gian nào trong năm để tôi có thể sắp xếp lịch tham dự cùng một vài đồng nghiệp của mình? Rất mong sớm nhận được phản hồi từ viện. Trân trọng cảm ơn.`,

  // 7 — hợp tác doanh nghiệp
  `Chúng tôi là một công ty công nghệ tài chính quy mô vừa, hiện có khoảng hai trăm nhân sự và đang trong giai đoạn mở rộng đội ngũ kỹ thuật khá nhanh, vì vậy chúng tôi rất quan tâm đến việc xây dựng quan hệ hợp tác lâu dài với các cơ sở đào tạo có chuyên môn phù hợp. Tôi muốn hỏi viện hiện đang hợp tác với những doanh nghiệp hay tổ chức nào, và hình thức hợp tác cụ thể là gì, chẳng hạn tiếp nhận sinh viên thực tập, tài trợ học bổng, đặt hàng đề tài nghiên cứu hay cùng xây dựng chương trình đào tạo? Nếu công ty chúng tôi muốn trở thành đối tác của viện thì quy trình sẽ diễn ra như thế nào, cần liên hệ với ai, chuẩn bị hồ sơ gì và thường mất bao lâu để hai bên đi đến ký kết chính thức? Chúng tôi đặc biệt quan tâm đến việc tiếp nhận sinh viên thực tập với số lượng tương đối lớn, khoảng mười lăm đến hai mươi bạn mỗi đợt, nên tôi muốn biết viện thường sắp xếp thực tập vào khoảng thời gian nào trong năm học, kéo dài bao nhiêu tuần và sinh viên ở giai đoạn đó đã có những kỹ năng nền tảng nào. Ngoài ra chúng tôi cũng sẵn sàng cử chuyên gia của công ty tham gia giảng dạy một số chuyên đề thực tế hoặc đồng hướng dẫn đồ án tốt nghiệp, không biết viện có cơ chế nào cho hình thức này hay không. Mong nhận được hồi âm sớm từ phía viện.`,

  // 8 — việc làm sau tốt nghiệp
  `Em sắp bước vào năm cuối và thú thật là em đang khá lo lắng về chuyện việc làm sau khi ra trường, nhất là khi em đọc thấy nhiều thông tin trái chiều về thị trường lao động ngành công nghệ trong thời gian gần đây. Em muốn hỏi tỷ lệ sinh viên của viện có việc làm sau khi tốt nghiệp là khoảng bao nhiêu phần trăm, và con số đó được thống kê sau bao lâu kể từ ngày tốt nghiệp, ba tháng, sáu tháng hay một năm ạ? Các anh chị khóa trước sau khi ra trường thường làm ở những vị trí nào và tại những loại doanh nghiệp nào, là ngân hàng, công ty chứng khoán, công ty công nghệ tài chính hay các công ty phần mềm nói chung? Mức lương khởi điểm trung bình của sinh viên mới tốt nghiệp vào khoảng bao nhiêu, và có sự chênh lệch lớn giữa các nhóm ngành trong viện hay không? Em cũng muốn biết viện có bộ phận nào hỗ trợ sinh viên về mặt hướng nghiệp không, chẳng hạn tổ chức ngày hội việc làm, kết nối với nhà tuyển dụng, hướng dẫn viết hồ sơ xin việc hay luyện tập phỏng vấn thử. Có mạng lưới cựu sinh viên nào đang hoạt động để các bạn khóa sau có thể kết nối và xin lời khuyên không ạ? Cuối cùng, theo kinh nghiệm của viện thì ngay từ bây giờ em nên chuẩn bị thêm những kỹ năng hay chứng chỉ nào để tăng cơ hội trúng tuyển vào các vị trí tốt? Em cảm ơn ạ.`,

  // 9 — cơ sở vật chất
  `Gia đình tôi ở tỉnh xa và cháu nhà tôi nếu đỗ sẽ phải ra Hà Nội trọ học, nên ngoài chuyện chương trình đào tạo thì tôi cũng rất quan tâm đến điều kiện học tập và sinh hoạt thực tế hằng ngày của các cháu tại trường. Tôi muốn hỏi viện đặt trụ sở ở địa chỉ nào, có nằm trong khuôn viên chính của Đại học Bách khoa Hà Nội hay ở một cơ sở riêng biệt, và việc di chuyển giữa các cơ sở có thuận tiện không? Về cơ sở vật chất phục vụ học tập, viện có bao nhiêu phòng học và phòng thực hành máy tính, cấu hình máy có đáp ứng được các môn học nặng về tính toán hay phân tích dữ liệu không, và sinh viên có được sử dụng phòng máy ngoài giờ lên lớp để tự học hay làm đồ án hay không? Thư viện của trường mở cửa đến mấy giờ, có khu vực tự học yên tĩnh và có đủ chỗ ngồi vào mùa thi hay không? Sinh viên có được đăng ký ở ký túc xá không, điều kiện xét duyệt như thế nào, mỗi phòng bao nhiêu người, chi phí một tháng khoảng bao nhiêu và có ưu tiên cho sinh viên năm nhất ở xa như cháu nhà tôi không? Xung quanh trường thì việc thuê trọ bên ngoài có dễ dàng không và giá cả trung bình vào khoảng bao nhiêu một tháng? Ngoài ra tôi cũng muốn biết trường có phòng y tế, căng tin và các câu lạc bộ thể thao cho sinh viên tham gia hay không.`,

  // 10 — học bổng
  `Em là sinh viên năm hai, kết quả học tập của em hiện ở mức khá giỏi với điểm trung bình tích lũy khoảng ba phẩy sáu trên thang bốn, và em đang rất muốn tìm hiểu kỹ về các cơ hội học bổng để giảm bớt gánh nặng tài chính cho bố mẹ ở quê. Em muốn hỏi viện và nhà trường hiện có những loại học bổng nào dành cho sinh viên, chẳng hạn học bổng khuyến khích học tập theo kỳ, học bổng từ doanh nghiệp tài trợ, học bổng dành cho sinh viên có hoàn cảnh khó khăn hay học bổng cho hoạt động nghiên cứu khoa học? Với mỗi loại thì tiêu chí xét duyệt cụ thể ra sao, cần điểm trung bình tối thiểu bao nhiêu, có yêu cầu về điểm rèn luyện hay hoạt động ngoại khóa không, và giá trị mỗi suất học bổng vào khoảng bao nhiêu, có tương đương một kỳ học phí hay không? Thời gian nộp hồ sơ xét học bổng thường vào khoảng tháng mấy trong năm học, và em cần chuẩn bị những giấy tờ gì, nộp trực tuyến hay nộp bản giấy tại văn phòng nào? Em cũng nghe nói có những học bổng trao đổi sinh viên hoặc học bổng du học ngắn hạn tại các trường đối tác ở nước ngoài, không biết viện có chương trình như vậy không, điều kiện tham gia là gì và yêu cầu trình độ tiếng Anh ở mức nào? Nếu em muốn xin học bổng ngay trong học kỳ này thì em nên bắt đầu từ đâu ạ?`,
];
